### ISSUE TITLE
CI fails to build CnoidRosUtils

### ISSUE THREAD

**Issue by mmurooka** [isri-aist/LocomanipController#8]
https://github.com/isri-aist/LocomanipController/actions/runs/6133946055/job/16646276004

```
/usr/bin/ld: cannot find -lfmt
collect2: error: ld returned 1 exit status
make[2]: *** [plugin/CMakeFiles/CnoidRosUtilsPlugin.dir/build.make:163: /home/runner/work/LocomanipController/LocomanipController/catkin_ws/src/isri-aist/CnoidRosUtils/plugin/lib/libCnoidRosUtilsPlugin.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1757: plugin/CMakeFiles/CnoidRosUtilsPlugin.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

Is this related to https://github.com/isri-aist/CnoidRosUtils/commit/dc57984656536b575a50b65003dbb4edc8587129 ?
FYI @gergondet

**Comment by gergondet** [comment]
Hi @mmurooka 

Yes it is. For some reasons, the push to master did not trigger the CI (maybe because it was the cron schedule desactivated it?)

The issue comes from the fact that `libcnoid-dev` did not depend on `libfmt-dev`. I have released a new version of the package that fixes it (and I have also rebased the package on the latest version of choreonoid but that's unrelated to this issue)

**Comment by mmurooka** [comment]
Thank you @gergondet 

I will cloes this issue now that the CI has passed.
